name: top-journal-bot

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: top-journal-bot:latest
    container_name: top-journal-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
